build: Run tasks 'static' and 'test' in sequence
The 'default' task launches 'static' and 'test' in parallel.

Since dev-dependencies were updated, running 'default'
leads to errors in 'static' - but there are no errors
when they are launched individually.

Error log (with truncated paths):

[20:03:27] Starting 'default'...
[20:03:27] Starting 'static'...
[20:03:27] Starting 'pre-test'...
[20:03:29] Finished 'pre-test' after 1.83 s
[20:03:29] Starting 'test'...
...
...
[20:03:32] Finished 'test' after 2.88 s

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: No ESLint configuration found.
  at Config.getLocalConfigHierarchy (.../node_modules/eslint/lib/config.js:254:39)
  at Config.getConfigHierarchy (.../node_modules/eslint/lib/config.js:180:43)
  at Config.getConfigVector (.../node_modules/eslint/lib/config.js:285:21)
  at Config.getConfig (.../node_modules/eslint/lib/config.js:328:29)
  at processText (.../node_modules/eslint/lib/cli-engine.js:158:33)
  at CLIEngine.executeOnText (.../node_modules/eslint/lib/cli-engine.js:606:17)
  at Transform.util.transform.e [as _transform] (.../node_modules/gulp-eslint/index.js:50:20)
  at Transform._read (_stream_transform.js:167:10)
  at Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:331:12)

Signed-off-by: Sanjeev Premi <spremi@ymail.com>